security:
    encoders:
        App\Entity\Utilisateur:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory: { memory: ~ }
        in_database:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: in_database

            logout:
                path: logout_route
            form_login:
                login_path: login_route
                check_path: login_route
                csrf_token_generator: security.csrf.token_manager
                #default_target_path: home_route
                failure_path: login_route
                
            access_denied_handler: App\Security\AccessDeniedHandler
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_PROPRIO
        ROLE_PROPRIO:       ROLE_USER