#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home_route:
  path: /
  controller: App\Controller\HomeController::index

contact_route:
  path: /contact
  controller: App\Controller\ContactController::index

logout_route:
  path: /logout