<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMqm0AdX\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMqm0AdX/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMqm0AdX.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMqm0AdX\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMqm0AdX\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Mqm0AdX',
    'container.build_id' => '8ee89b34',
    'container.build_time' => 1539000232,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMqm0AdX');
