<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMPQyTh2\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMPQyTh2/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMPQyTh2.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMPQyTh2\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMPQyTh2\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MPQyTh2',
    'container.build_id' => 'a24892c6',
    'container.build_time' => 1538992976,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMPQyTh2');
