<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2a6IPn\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2a6IPn/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX2a6IPn.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX2a6IPn\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerX2a6IPn\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'X2a6IPn',
    'container.build_id' => '963170b7',
    'container.build_time' => 1538983719,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2a6IPn');
